### ISSUE TITLE
Crash after dragging any asset from FileSystem into an EventGraph and then trying to drag the value connection from the resulting node

### ISSUE THREAD

**Issue by tarragonfly** [Vahera/godot-orchestrator#96] opened 2024-02-03 01:02 UTC
### Describe the bug

Editor crash

### Expected behavior

Editor shouldn't crash

### Actual behavior

Editor crashes

### How to Reproduce?

1. Drag any asset from FileSystem to EventGraph. I've tried with .tscn, .gd and .os. Same result for all.
2. In the popup box from the two options, select "Get Path", which adds a GetResourcePath node.
3. Grab the GetResourcePath node's value connection and start dragging it
4. Notice how editor crashes

### Godot full version

4.2.1

### Orchestrator version

2.0.dev2

**Comment by Naros** [comment] 2024-02-03 01:33
Hi @tarragonfly, I am not able to reproduce this on `main`, can you confirm whether you're using the special build I did for GH-82 found in this issue, https://github.com/Vahera/godot-orchestrator/issues/82.  If you are not, can you replace the shard library for dev2 with the build in this issue for your OS and let me know if that solves the issue.

**Comment by tarragonfly** [comment] 2024-02-03 01:44
> Hi @tarragonfly, I am not able to reproduce this on `main`, can you confirm whether you're using the special build I did for [GH-82](https://github.com/Vahera/godot-orchestrator/issues/82) found in this issue, #82. If you are not, can you replace the shard library for dev2 with the build in this issue for your OS and let me know if that solves the issue.

Yea, the special build addressed this crash. Case closed.

**Comment by Naros** [comment] 2024-02-03 01:48
Great, I'll go ahead and close this, and the fix will be in dev3, likely sometime this weekend.

**Closed by Naros** 2024-02-03 01:48 UTC
Labels: kind/bug
