### ISSUE TITLE
get_setting returning null in all scenarios

### ISSUE THREAD

**Issue by TBNEO** [Vahera/godot-orchestrator#240] opened 2024-04-07 19:14 UTC
### Describe the bug

The get_setting node in the ProjectSettings singleton constantly returns `null`.

### Expected behavior

get_setting should normally return the value of the setting, accessed by inputting the path to it.

![image](https://github.com/Vahera/godot-orchestrator/assets/121733211/c3829cac-826a-476b-ae21-abcd20e208fd)

### Actual behavior

Currently, it returns `null` in all cases.

### Godot full version

4.2

### Orchestrator version

v2.0-stable

**Comment by Naros** [comment] 2024-04-07 19:30
As discussed in Discord, the issue is that the `Call Function` node does not properly adhere to the `PropertyInfo` usage masks for the method's return value, treating the function call as though it has no return value when it does, but it's a Variant.  I seem to recall we fixed this issue previously but maybe it wasn't fixed in all use cases.

**Closed** 2024-04-07 20:36 UTC
Labels: kind/bug, bug/confirmed, 2.0
